// aslWordData.js — 250 詞完整資料庫
// word: Kaggle 模型 key | display: 英文顯示名 | zh: 中文 | cat: 類別 | hint: 手勢提示

const ANIMAL   = 'animal';
const FOOD     = 'food';
const PEOPLE   = 'people';
const COLOR    = 'color';
const HOME     = 'home';
const NATURE   = 'nature';
const ACTION   = 'action';
const FEELING  = 'feeling';
const BODY     = 'body';
const OBJECT   = 'object';
const COMMON   = 'common';
const TIME     = 'time';

// [word, display, zh, category, hint]
const RAW = [
  ['TV',           'TV',             '電視',    OBJECT,  '指向電視，做看電視的動作'],
  ['after',        'After',          '之後',    TIME,    '一手在另一手前方，向前滑動'],
  ['airplane',     'Airplane',       '飛機',    OBJECT,  'Y 型手向前移動模擬飛機飛行'],
  ['all',          'All',            '全部',    COMMON,  '一手掌心朝外，環繞翻轉向另一手'],
  ['alligator',    'Alligator',      '鱷魚',    ANIMAL,  '雙手張合像鱷魚嘴巴咬合'],
  ['animal',       'Animal',         '動物',    ANIMAL,  '雙手指尖放胸口，前後搖動像動物爪'],
  ['another',      'Another',        '另一個',  COMMON,  'A 手拇指朝上，翻轉移向另一側'],
  ['any',          'Any',            '任何',    COMMON,  'A 手朝下旋轉向前'],
  ['apple',        'Apple',          '蘋果',    FOOD,    'X 手指放臉頰旁扭轉'],
  ['arm',          'Arm',            '手臂',    BODY,    '手指沿前臂從手腕滑向肩膀'],
  ['aunt',         'Aunt',           '阿姨',    PEOPLE,  'A 手在臉頰旁畫圓'],
  ['awake',        'Awake',          '醒著',    FEELING, '雙手指尖輕觸閉眼，張開模擬睜眼'],
  ['backyard',     'Backyard',       '後院',    HOME,    '先比 BACK 再比 YARD'],
  ['bad',          'Bad',            '壞/不好', FEELING, '手掌靠近嘴，向下翻轉'],
  ['balloon',      'Balloon',        '氣球',    OBJECT,  '雙手模擬吹氣球膨脹的動作'],
  ['bath',         'Bath',           '洗澡',    ACTION,  'A 手在胸前上下摩擦像洗澡'],
  ['because',      'Because',        '因為',    COMMON,  '食指觸太陽穴，移出後彎成 B'],
  ['bed',          'Bed',            '床',      HOME,    '雙手合掌貼臉頰，頭側斜像躺在床上'],
  ['bedroom',      'Bedroom',        '臥室',    HOME,    '先比 BED 再比 ROOM'],
  ['bee',          'Bee',            '蜜蜂',    ANIMAL,  'B 手觸臉頰，再用另一手揮去（被蜜蜂螫）'],
  ['before',       'Before',         '之前',    TIME,    '一手從另一手後方移向前'],
  ['beside',       'Beside',         '旁邊',    COMMON,  '平手在另一平手旁移動'],
  ['better',       'Better',         '更好',    FEELING, '平手從嘴邊向上移動，握成 A 手'],
  ['bird',         'Bird',           '鳥',      ANIMAL,  'G 手放嘴邊開合模擬鳥嘴'],
  ['black',        'Black',          '黑色',    COLOR,   '食指從左到右橫過額頭'],
  ['blow',         'Blow',           '吹',      ACTION,  '嘴做吹的動作，手指向前'],
  ['blue',         'Blue',           '藍色',    COLOR,   'B 手在側方輕輕搖動'],
  ['boat',         'Boat',           '船',      OBJECT,  '雙手杯形朝上，前後搖動模擬小船'],
  ['book',         'Book',           '書',      OBJECT,  '雙手合掌再打開，像翻開一本書'],
  ['boy',          'Boy',            '男孩',    PEOPLE,  '模擬摸帽緣後手握合（棒球帽）'],
  ['brother',      'Brother',        '兄弟',    PEOPLE,  'L 手從額頭滑向另一 L 手'],
  ['brown',        'Brown',          '棕色',    COLOR,   'B 手沿臉頰向下滑'],
  ['bug',          'Bug',            '蟲子',    ANIMAL,  '拇指撐在鼻子上，兩指彎曲像觸角'],
  ['bye',          'Bye',            '再見',    COMMON,  '揮手道別'],
  ['callonphone',  'Call On Phone',  '打電話',  ACTION,  'Y 手放耳邊（手機手勢）'],
  ['can',          'Can',            '可以',    COMMON,  '雙 S 手交替向下移動'],
  ['car',          'Car',            '汽車',    OBJECT,  '雙手模擬握住方向盤轉動'],
  ['carrot',       'Carrot',         '胡蘿蔔',  FOOD,    'X 手指放嘴角旁扭轉'],
  ['cat',          'Cat',            '貓',      ANIMAL,  '拇指食指在臉頰旁向外拉兩次（貓鬚）'],
  ['cereal',       'Cereal',         '穀片',    FOOD,    'X 手指沿下巴滑動，模擬湯匙舀麥片'],
  ['chair',        'Chair',          '椅子',    HOME,    'V 手指勾在另一手的兩指上，模擬坐下'],
  ['cheek',        'Cheek',          '臉頰',    BODY,    '指向或輕觸臉頰'],
  ['child',        'Child',          '孩子',    PEOPLE,  '平手向下拍動，模擬拍孩子頭'],
  ['chin',         'Chin',           '下巴',    BODY,    '一指輕觸下巴'],
  ['chocolate',    'Chocolate',      '巧克力',  FOOD,    'C 手在另一手背上畫圓'],
  ['clean',        'Clean',          '乾淨',    ACTION,  '平手在另一平手上滑過'],
  ['close',        'Close',          '關閉',    ACTION,  '雙 B 手靠攏合起'],
  ['closet',       'Closet',         '衣櫃',    HOME,    'C 手模擬衣櫃門打開關上'],
  ['cloud',        'Cloud',          '雲',      NATURE,  '雙 C 手在頭上方交替畫圓'],
  ['clown',        'Clown',          '小丑',    PEOPLE,  'C 手在鼻子上彈開（小丑大鼻子）'],
  ['cow',          'Cow',            '牛',      ANIMAL,  'Y 手拇指放太陽穴，扭轉（牛角）'],
  ['cowboy',       'Cowboy',         '牛仔',    PEOPLE,  'C 手放太陽穴後做出拔槍動作'],
  ['cry',          'Cry',            '哭',      ACTION,  '食指從眼睛下方畫下一條淚痕'],
  ['cut',          'Cut',            '剪/切',   ACTION,  'V 手模擬剪刀剪切動作'],
  ['cute',         'Cute',           '可愛',    FEELING, 'U 手指從下巴輕刷向下'],
  ['dad',          'Dad',            '爸爸',    PEOPLE,  '五指張開，拇指頂額頭'],
  ['dance',        'Dance',          '跳舞',    ACTION,  'V 手在另一手掌上左右搖擺'],
  ['dirty',        'Dirty',          '髒',      FEELING, '五指張開放下巴下方搖動'],
  ['dog',          'Dog',            '狗',      ANIMAL,  '拍大腿後打響指'],
  ['doll',         'Doll',           '娃娃',    OBJECT,  '彎 X 手從鼻子向下滑'],
  ['donkey',       'Donkey',         '驢子',    ANIMAL,  'B 手彎腕放側頭，上下拍動（驢耳朵）'],
  ['down',         'Down',           '向下',    COMMON,  '食指朝下指'],
  ['drawer',       'Drawer',         '抽屜',    HOME,    '雙手向外拉，模擬拉出抽屜'],
  ['drink',        'Drink',          '喝',      ACTION,  'C 手傾斜向嘴，模擬喝飲料'],
  ['drop',         'Drop',           '掉落',    ACTION,  '握住手形張開手指，手向下'],
  ['dry',          'Dry',            '乾燥',    ACTION,  'X 手從下巴一側拖到另一側'],
  ['dryer',        'Dryer',          '烘乾機',  HOME,    'D 手在另一臂內畫圓（滾筒）'],
  ['duck',         'Duck',           '鴨子',    ANIMAL,  '三指在嘴邊開合，模擬鴨嘴'],
  ['ear',          'Ear',            '耳朵',    BODY,    '指向或輕觸耳朵'],
  ['elephant',     'Elephant',       '大象',    ANIMAL,  'E 手從鼻子描出象鼻弧形向下'],
  ['empty',        'Empty',          '空的',    FEELING, '中指在另一手背上橫向滑過'],
  ['every',        'Every',          '每個',    COMMON,  'A 手沿另一 A 手指節向下滑'],
  ['eye',          'Eye',            '眼睛',    BODY,    '兩指指向雙眼'],
  ['face',         'Face',           '臉',      BODY,    '食指繞臉畫一個圓'],
  ['fall',         'Fall',           '跌倒',    ACTION,  'V 手站在掌心，向前傾倒'],
  ['farm',         'Farm',           '農場',    HOME,    '五指張開，拇指從下巴一端滑到另一端'],
  ['fast',         'Fast',           '快',      FEELING, 'L 手食指快速彈出'],
  ['feet',         'Feet',           '腳',      BODY,    '指向下方腳的位置'],
  ['find',         'Find',           '找到',    ACTION,  'F 手向上提起，像找到東西'],
  ['fine',         'Fine',           '很好',    FEELING, '拇指觸胸口'],
  ['finger',       'Finger',         '手指',    BODY,    '指向或觸摸手指'],
  ['finish',       'Finish',         '完成',    ACTION,  '雙五指朝外，快速向內翻轉'],
  ['fireman',      'Fireman',        '消防員',  PEOPLE,  'F 手在額頭拍（消防帽）'],
  ['first',        'First',          '第一',    COMMON,  'A 手食指彈出（第一根手指）'],
  ['fish',         'Fish',           '魚',      ANIMAL,  '平手朝前，手腕左右擺動像魚游泳'],
  ['flag',         'Flag',           '旗子',    OBJECT,  'F 手在立起手肘上揮動'],
  ['flower',       'Flower',         '花',      NATURE,  'O 手從鼻子一側移到另一側（花香）'],
  ['food',         'Food',           '食物',    FOOD,    '手指合攏輕點嘴唇'],
  ['for',          'For',            '為了',    COMMON,  '食指觸太陽穴，向前扭轉'],
  ['frenchfries',  'French Fries',   '薯條',    FOOD,    'F 手在空中彈跳兩下'],
  ['frog',         'Frog',           '青蛙',    ANIMAL,  '握拳放下巴，兩指彈出兩次（青蛙舌頭）'],
  ['garbage',      'Garbage',        '垃圾',    OBJECT,  '手放下巴後甩向外'],
  ['gift',         'Gift',           '禮物',    OBJECT,  '雙彎手面對，同時向前伸出'],
  ['giraffe',      'Giraffe',        '長頸鹿',  ANIMAL,  'C 手從喉嚨沿脖子向上延伸'],
  ['girl',         'Girl',           '女孩',    PEOPLE,  'A 手拇指沿下巴線向下滑'],
  ['give',         'Give',           '給',      ACTION,  '彎手向前推出'],
  ['glasswindow',  'Glass Window',   '玻璃窗',  HOME,    '雙 G 手描繪窗框形狀'],
  ['go',           'Go',             '去',      ACTION,  '雙食指朝前方彎曲指出'],
  ['goose',        'Goose',          '鵝',      ANIMAL,  '手模擬鵝嘴在嘴邊開合'],
  ['grandma',      'Grandma',        '奶奶',    PEOPLE,  '五指放下巴，向前弧形跳兩次'],
  ['grandpa',      'Grandpa',        '爺爺',    PEOPLE,  '五指放額頭，向前弧形跳兩次'],
  ['grass',        'Grass',          '草',      NATURE,  'G 手沿下巴刷過'],
  ['green',        'Green',          '綠色',    COLOR,   'G 手輕微搖動'],
  ['gum',          'Gum',            '口香糖',  FOOD,    'U 手指在臉頰側滑動（咀嚼動作）'],
  ['hair',         'Hair',           '頭髮',    BODY,    '拇指食指夾住頭髮輕提'],
  ['happy',        'Happy',          '開心',    FEELING, '平手在胸前向上刷兩次'],
  ['hat',          'Hat',            '帽子',    OBJECT,  '拍頭頂模擬戴帽'],
  ['hate',         'Hate',           '討厭',    FEELING, '中指從 8 手彈出'],
  ['have',         'Have',           '有',      COMMON,  '彎手指尖觸胸'],
  ['haveto',       'Have To',        '必須',    COMMON,  'X 手向前扭轉推出'],
  ['head',         'Head',           '頭',      BODY,    '彎手輕拍側頭兩次'],
  ['hear',         'Hear',           '聽',      ACTION,  '食指指向耳朵'],
  ['helicopter',   'Helicopter',     '直升機',  OBJECT,  'L 手在 S 手上旋轉（螺旋槳）'],
  ['hello',        'Hello',          '你好',    COMMON,  '張開手掌放額頭旁，向外揮出（敬禮）'],
  ['hen',          'Hen',            '母雞',    ANIMAL,  '手在嘴邊高度開合（母雞嘴）'],
  ['hesheit',      'He / She / It',  '他/她/它', COMMON, '食指向前指'],
  ['hide',         'Hide',           '躲藏',    ACTION,  'A 手藏入另一彎手下'],
  ['high',         'High',           '高',      FEELING, 'H 手向上移動'],
  ['home',         'Home',           '家',      HOME,    'O 手觸臉頰，再移到嘴角'],
  ['horse',        'Horse',          '馬',      ANIMAL,  'U 手放太陽穴，上下拍動（馬耳）'],
  ['hot',          'Hot',            '熱',      FEELING, '爪手放嘴邊，快速向外翻甩'],
  ['hungry',       'Hungry',         '飢餓',    FEELING, 'C 手從喉嚨沿胸向下'],
  ['icecream',     'Ice Cream',      '冰淇淋',  FOOD,    'S 手向下舔，模擬舔冰淇淋'],
  ['if',           'If',             '如果',    COMMON,  'F 手在空中上下輕彈'],
  ['into',         'Into',           '進入',    COMMON,  '一手手指穿入另一手形成的圈中'],
  ['jacket',       'Jacket',         '夾克',    OBJECT,  '雙 A 手從胸前向下拉（穿夾克）'],
  ['jeans',        'Jeans',          '牛仔褲',  OBJECT,  'J 手沿大腿向下描繪'],
  ['jump',         'Jump',           '跳',      ACTION,  'V 手站在掌心後跳起'],
  ['kiss',         'Kiss',           '親吻',    ACTION,  '手指合攏觸嘴，再輕點臉頰'],
  ['kitty',        'Kitty',          '小貓',    ANIMAL,  '拇指食指在臉頰旁向外拉兩次（貓鬚）'],
  ['lamp',         'Lamp',           '燈',      HOME,    'L 手向上張開手指（燈光散射）'],
  ['later',        'Later',          '之後',    TIME,    'L 手在掌心上向前傾'],
  ['like',         'Like',           '喜歡',    FEELING, '中指拇指夾胸口，向外拉伸'],
  ['lion',         'Lion',           '獅子',    ANIMAL,  '爪手在頭頂搖動（獅子鬃毛）'],
  ['lips',         'Lips',           '嘴唇',    BODY,    '食指描繪嘴唇輪廓'],
  ['listen',       'Listen',         '聽',      ACTION,  '手掌彎曲放耳後，像側耳傾聽'],
  ['look',         'Look',           '看',      ACTION,  'V 手從眼睛指向前方'],
  ['loud',         'Loud',           '大聲',    FEELING, '雙 L 手在耳邊向外甩'],
  ['mad',          'Mad',            '生氣',    FEELING, '爪手在臉前，緊繃向上拉'],
  ['make',         'Make',           '製作',    ACTION,  '雙 S 手交疊，扭轉'],
  ['man',          'Man',            '男人',    PEOPLE,  '張開手，拇指觸額頭後再觸下巴'],
  ['many',         'Many',           '很多',    COMMON,  '雙 S 手快速張開（手指散射）'],
  ['milk',         'Milk',           '牛奶',    FOOD,    '握拳開合交替，模擬擠奶'],
  ['minemy',       'Mine / My',      '我的',    COMMON,  '平手按壓在胸口'],
  ['mitten',       'Mitten',         '手套',    OBJECT,  '一手描繪另一手的手套形狀'],
  ['mom',          'Mom',            '媽媽',    PEOPLE,  '五指張開，拇指觸下巴'],
  ['moon',         'Moon',           '月亮',    NATURE,  'C 手放太陽穴模擬月彎形'],
  ['morning',      'Morning',        '早晨',    TIME,    '平手從另一手肘下方升起，像日出'],
  ['mouse',        'Mouse',          '老鼠',    ANIMAL,  '食指在鼻子上橫刷兩次'],
  ['mouth',        'Mouth',          '嘴巴',    BODY,    '食指圈住嘴巴'],
  ['nap',          'Nap',            '小睡',    ACTION,  '彎手放頭側，模擬頭枕在手上睡覺'],
  ['napkin',       'Napkin',         '餐巾',    OBJECT,  'N 手在嘴邊擦拭'],
  ['night',        'Night',          '夜晚',    TIME,    '彎手向下弧過，像太陽落地平線'],
  ['no',           'No',             '不',      COMMON,  '中食指夾拇指，快速開合兩次'],
  ['noisy',        'Noisy',          '吵鬧',    FEELING, '張開手在兩耳邊搖動'],
  ['nose',         'Nose',           '鼻子',    BODY,    '指向鼻子'],
  ['not',          'Not',            '不是',    COMMON,  'A 手拇指從下巴下方向前彈出'],
  ['now',          'Now',            '現在',    TIME,    'Y 手在前方向下落'],
  ['nuts',         'Nuts',           '堅果',    FOOD,    'A 手拇指在門牙後向前彈出'],
  ['old',          'Old',            '老的',    FEELING, 'C 手從下巴向下移動，像撫摸鬍鬚'],
  ['on',           'On',             '在上面',  COMMON,  '平手落在另一平手上方'],
  ['open',         'Open',           '打開',    ACTION,  '雙 B 手並排，向外分開'],
  ['orange',       'Orange',         '橘色',    COLOR,   'C 手在下巴處反覆握緊（擠橘子）'],
  ['outside',      'Outside',        '戶外',    HOME,    'O 手從另一 O 手中向外拉出'],
  ['owie',         'Owie',           '受傷了',  FEELING, '指向受傷位置或雙食指相碰'],
  ['owl',          'Owl',            '貓頭鷹',  ANIMAL,  'O 手放兩眼前，左右轉動像貓頭鷹'],
  ['pajamas',      'Pajamas',        '睡衣',    OBJECT,  'P 手在胸前做 J 動作，再做睡覺手勢'],
  ['pen',          'Pen',            '筆',      OBJECT,  '模擬握筆在掌心書寫'],
  ['pencil',       'Pencil',         '鉛筆',    OBJECT,  '舔拇指食指後，在掌心模擬寫字'],
  ['penny',        'Penny',          '一分錢',  OBJECT,  '彎食指觸太陽穴'],
  ['person',       'Person',         '人',      PEOPLE,  'P 手沿身體兩側向下'],
  ['pig',          'Pig',            '豬',      ANIMAL,  '平手彎曲放下巴下，手指搖動'],
  ['pizza',        'Pizza',          '披薩',    FOOD,    'P 手在空中描繪 Z 形'],
  ['please',       'Please',         '請',      COMMON,  '手掌貼胸口，順時針畫圓'],
  ['police',       'Police',         '警察',    PEOPLE,  'C 手拍胸口左側（警徽位置）'],
  ['pool',         'Pool',           '游泳池',  HOME,    'P 手模擬游泳動作'],
  ['potty',        'Potty',          '廁所',    HOME,    'T 手左右搖動'],
  ['pretend',      'Pretend',        '假裝',    ACTION,  'P 手放太陽穴，手指向外彈出'],
  ['pretty',       'Pretty',         '漂亮',    FEELING, '張開手繞臉畫圓，最後握合'],
  ['puppy',        'Puppy',          '小狗',    ANIMAL,  '拍大腿後打響指兩次'],
  ['puzzle',       'Puzzle',         '拼圖',    OBJECT,  '雙彎手互相勾扣再分開'],
  ['quiet',        'Quiet',          '安靜',    FEELING, '食指輕放嘴唇，雙手再向下壓'],
  ['radio',        'Radio',          '收音機',  OBJECT,  '彎手放耳邊（像戴耳機）'],
  ['rain',         'Rain',           '雨',      NATURE,  '雙爪手交替向下移動（雨水落下）'],
  ['read',         'Read',           '閱讀',    ACTION,  'V 手掃描另一平手（眼睛掃讀）'],
  ['red',          'Red',            '紅色',    COLOR,   '食指從嘴唇向下刷'],
  ['refrigerator', 'Refrigerator',   '冰箱',    HOME,    'R 手搖動（像冷得發抖）'],
  ['ride',         'Ride',           '騎',      ACTION,  '彎手指勾住另一食指（騎馬）'],
  ['room',         'Room',           '房間',    HOME,    'R 手圍成四邊形（房間平面圖）'],
  ['sad',          'Sad',            '悲傷',    FEELING, '張開雙手從臉旁向下滑（臉垮下來）'],
  ['same',         'Same',           '一樣',    COMMON,  'Y 手左右移動'],
  ['say',          'Say',            '說',      ACTION,  '食指在嘴邊畫圓'],
  ['scissors',     'Scissors',       '剪刀',    OBJECT,  'V 手模擬剪刀開合'],
  ['see',          'See',            '看見',    ACTION,  'V 手從眼睛指向前方'],
  ['shhh',         'Shhh',           '噓',      COMMON,  '食指放嘴唇上，像噓的動作'],
  ['shirt',        'Shirt',          '衣服',    OBJECT,  '雙手捏胸前衣服'],
  ['shoe',         'Shoe',           '鞋子',    OBJECT,  '雙 S 手互相碰擊兩次'],
  ['shower',       'Shower',         '淋浴',    ACTION,  'S 手在頭頂，手指向下張開（蓮蓬頭）'],
  ['sick',         'Sick',           '生病',    FEELING, '中指觸額頭，另一中指觸胃部'],
  ['sleep',        'Sleep',          '睡覺',    ACTION,  '張開手在臉前合攏，頭微側（入睡）'],
  ['sleepy',       'Sleepy',         '想睡',    FEELING, '張開手緩緩靠近臉，像睏倦閉眼'],
  ['smile',        'Smile',          '微笑',    ACTION,  '雙食指從嘴角向上拉（微笑形狀）'],
  ['snack',        'Snack',          '點心',    FOOD,    'S 手手指輕咬（吃東西）'],
  ['snow',         'Snow',           '雪',      NATURE,  '雙手手指搖動，緩緩向下飄（雪花）'],
  ['stairs',       'Stairs',         '樓梯',    HOME,    '食中指交替向上，模擬走樓梯'],
  ['stay',         'Stay',           '留下',    ACTION,  'Y 手向下穩定壓'],
  ['sticky',       'Sticky',         '黏的',    FEELING, '拇指和中指摩擦，手向上提（黏黏的）'],
  ['store',        'Store',          '商店',    HOME,    '雙彎 O 手向前下搖動兩次'],
  ['story',        'Story',          '故事',    COMMON,  '雙鉤食指相扣，交替拉開（串故事）'],
  ['stuck',        'Stuck',          '卡住',    ACTION,  'V 手指觸喉嚨（卡住）'],
  ['sun',          'Sun',            '太陽',    NATURE,  'C 手在太陽穴上方，向上張開（陽光）'],
  ['table',        'Table',          '桌子',    HOME,    '雙臂水平疊放，模擬桌面'],
  ['talk',         'Talk',           '說話',    ACTION,  '雙食指在嘴邊交替點動'],
  ['taste',        'Taste',          '嚐',      ACTION,  '中指輕觸嘴唇'],
  ['thankyou',     'Thank You',      '謝謝',    COMMON,  '手指輕觸嘴唇，向前伸出（送出謝意）'],
  ['that',         'That',           '那個',    COMMON,  'Y 手落在另一平手掌心'],
  ['there',        'There',          '那裡',    COMMON,  '食指指向特定方向'],
  ['think',        'Think',          '思考',    ACTION,  '食指在太陽穴旁畫圓'],
  ['thirsty',      'Thirsty',        '口渴',    FEELING, '食指從喉嚨向下劃'],
  ['tiger',        'Tiger',          '老虎',    ANIMAL,  '爪手從臉頰向外拉，模擬虎紋'],
  ['time',         'Time',           '時間',    TIME,    '彎食指輕點手腕（手錶位置）'],
  ['tomorrow',     'Tomorrow',       '明天',    TIME,    'A 手放臉頰，向前弧形移動'],
  ['tongue',       'Tongue',         '舌頭',    BODY,    '指向或輕伸舌頭'],
  ['tooth',        'Tooth',          '牙齒',    BODY,    'X 手輕點牙齒'],
  ['toothbrush',   'Toothbrush',     '牙刷',    OBJECT,  '食指在牙齒上左右刷動'],
  ['touch',        'Touch',          '觸摸',    ACTION,  '中指輕點另一手背'],
  ['toy',          'Toy',            '玩具',    OBJECT,  'T 手左右搖動'],
  ['tree',         'Tree',           '樹',      NATURE,  '手肘立起，五指張開搖動（大樹）'],
  ['uncle',        'Uncle',          '叔叔',    PEOPLE,  'U 手在太陽穴旁畫圓'],
  ['underwear',    'Underwear',       '內褲',   OBJECT,  'U 手在腰部向內刷兩次'],
  ['up',           'Up',             '向上',    COMMON,  '食指朝上指'],
  ['vacuum',       'Vacuum',         '吸塵器',  OBJECT,  'V 手向前推，模擬推吸塵器'],
  ['wait',         'Wait',           '等待',    ACTION,  '雙彎手手指搖動（等待）'],
  ['wake',         'Wake',           '醒來',    ACTION,  'L 手在閉眼旁，手指快速張開（睜眼）'],
  ['water',        'Water',          '水',      FOOD,    'W 手輕點下巴兩次'],
  ['wet',          'Wet',            '濕的',    FEELING, 'W 手反覆握緊（濕透）'],
  ['weus',         'We / Us',        '我們',    COMMON,  '彎食指從一側移到另一側'],
  ['where',        'Where',          '哪裡',    COMMON,  '食指左右搖動'],
  ['white',        'White',          '白色',    COLOR,   '張開手放胸口，向外握成 O 手'],
  ['who',          'Who',            '誰',      COMMON,  '拇指觸下巴，食指畫圓'],
  ['why',          'Why',            '為什麼',  COMMON,  '中指觸額頭，拿出 Y 手'],
  ['will',         'Will',           '將會',    COMMON,  '張開手放臉頰，向前移動'],
  ['wolf',         'Wolf',           '狼',      ANIMAL,  '張開手放鼻子前，合成 O（狼嘴）'],
  ['yellow',       'Yellow',         '黃色',    COLOR,   'Y 手輕搖'],
  ['yes',          'Yes',            '是',      COMMON,  'S 手上下點動，像點頭'],
  ['yesterday',    'Yesterday',      '昨天',    TIME,    'Y 手放臉頰，向後弧形移動'],
  ['yourself',     'Yourself',       '你自己',  COMMON,  'A 手向對方伸出'],
  ['yucky',        'Yucky',          '噁心',    FEELING, 'Y 手放下巴，搖動手指'],
  ['zebra',        'Zebra',          '斑馬',    ANIMAL,  '雙爪手交替在軀幹上描繪（斑紋）'],
  ['zipper',       'Zipper',         '拉鍊',    OBJECT,  'Z 手在胸前向上描繪拉拉鍊'],
];

// 類別資訊
export const CATEGORIES = [
  { key: 'all',     label: '全部',   emoji: '📋' },
  { key: ANIMAL,   label: '動物',   emoji: '🐾' },
  { key: FOOD,     label: '食物',   emoji: '🍎' },
  { key: PEOPLE,   label: '人物',   emoji: '👥' },
  { key: COLOR,    label: '顏色',   emoji: '🌈' },
  { key: HOME,     label: '家居',   emoji: '🏠' },
  { key: NATURE,   label: '自然',   emoji: '🌿' },
  { key: ACTION,   label: '動作',   emoji: '🏃' },
  { key: FEELING,  label: '情緒',   emoji: '😊' },
  { key: BODY,     label: '身體',   emoji: '🧍' },
  { key: OBJECT,   label: '物品',   emoji: '📦' },
  { key: COMMON,   label: '常用',   emoji: '💬' },
  { key: TIME,     label: '時間',   emoji: '⏰' },
];

// 完整詞彙資料（計算生成）
export const WORD_DATA = RAW.map(([word, display, zh, category, hint]) => ({
  word,
  display,
  zh,
  category,
  hint,
  ytSearch: `ASL ${display} sign language`,
}));

// key → data 快速查找
export const WORD_MAP = Object.fromEntries(WORD_DATA.map(d => [d.word, d]));

// 取得顯示名稱（含 fallback）
export function getDisplay(word) {
  return WORD_MAP[word]?.display || word.charAt(0).toUpperCase() + word.slice(1);
}

// 取得中文（含 fallback）
export function getZh(word) {
  return WORD_MAP[word]?.zh || '';
}
